# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/**"
          - "eslint-plugin-react"
          - "eslint-plugin-react-hooks"
      react-router:
        patterns:
          - "@types/react-router-dom"
          - "react-router-dom"
      vite:
        patterns:
          - "vite"
          - "vitest"
          - "vite-tsconfig-paths"
          - "@vitejs/**"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
